application: apostagol20152016
version: 1
runtime: php55
api_version: 1
handlers:
- url: /
  script: index.php
- url: /div_minhasapostas.php
  script: div_minhasapostas.php 
- url: /div_enviaapostas.php
  script: div_enviaapostas.php 
- url: /div_caixa.php
  script: div_caixa.php 
- url: /div_RANK.php
  script: div_RANK.php 
  
- url: /inicio.php
  script: inicio.php  
- url: /consultadb.php
  script: consultadb.php
- url: /gerencia.php
  script: gerencia.php
- url: /rescript.php
  script: rescript.php
- url: /data.php
  script: data.php
- url: /atualiza.php
  script: atualiza.php
- url: /usuario_aposta.php
  script: usuario_aposta.php
- url: /get-data.php
  script: get-data.php
- url: /javascript.php
  script: javascript.php
- url: /proccess_form.php
  script: proccess_form.php

