application: hazel-proxy-88217
version: 1
runtime: php
api_version: 1
handlers:
- url: /
  script: inicio.php
- url: /consultadb.php
  script: consultadb.php
- url: /gerencia.php
  script: gerencia.php
- url: /rescript.php
  script: rescript.php
- url: /data.php
  script: data.php
- url: /atualiza.php
  script: atualiza.php

