application: hazel-proxy-88217
version: 1
runtime: php
api_version: 1
handlers:
- url: /
  script: index.php
- url: /inicio.php
  script: inicio.php  
- url: /consultadb.php
  script: consultadb.php
- url: /gerencia.php
  script: gerencia.php
- url: /rescript.php
  script: rescript.php
- url: /data.php
  script: data.php
- url: /atualiza.php
  script: atualiza.php
- url: /usuario_aposta.php
  script: usuario_aposta.php
- url: /get-data.php
  script: get-data.php
- url: /javascript.php
  script: javascript.php
- url: /proccess_form.php
  script: proccess_form.php

